Repository peter-szrnka/give-my-secret, pull requests merged in 2023-01, with the labels that each got.

#3 GMS-3 Fix of keystoreserviceimpltest
  code/gms-backend/src/test/java/io/github/gms/secure/service/impl/KeystoreServiceImplTest.java
Labels: bug

#5 GMS-4 New GitHub Actions file
  .github/workflows/sonarcloud.yml
Labels: enhancement

#7 GMS-5 sonarcloud fixes
  code/gms-backend/src/main/java/io/github/gms/auth/config/SecurityConfig.java
  code/gms-backend/src/main/java/io/github/gms/auth/model/AuthenticationResponse.java
  code/gms-backend/src/main/java/io/github/gms/common/config/ApplicationConfig.java
  code/gms-backend/src/main/java/io/github/gms/common/config/FilterConfig.java
  code/gms-backend/src/main/java/io/github/gms/common/model/KeystorePair.java
  code/gms-backend/src/main/java/io/github/gms/common/types/Pair.java
  code/gms-backend/src/main/java/io/github/gms/common/util/DemoDataProviderService.java
Labels: enhancement

#9 GMS-7 remove codecov code coverage check and badge
  .github/workflows/code-quality-check-backend.yml
  .github/workflows/code-quality-check-frontend.yml
  .github/workflows/sonarcloud-backend.yml
  .github/workflows/sonarcloud-frontend.yml
  README.md
Labels: enhancement

#12 GMS-9 expose encryption algorythm as an external property
  batch-files/db-authentication/docker-compose.yml
  batch-files/db-authentication/env-mariadb.txt
  batch-files/db-authentication/env-mssql.txt
  batch-files/db-authentication/env-mysql.txt
  batch-files/db-authentication/env-postgresql.txt
  batch-files/ldap-authentication/docker-compose.yml
  batch-files/ldap-authentication/env-mariadb-and-ldap.txt
  batch-files/ldap-authentication/env-mssql-and-ldap.txt
  batch-files/ldap-authentication/env-mysql-and-ldap.txt
  batch-files/ldap-authentication/env-postgresql-and-ldap.txt
  code/gms-backend/src/main/java/io/github/gms/common/db/converter/EncryptedFieldConverter.java
  code/gms-backend/src/main/resources/application.properties
  code/gms-backend/src/test/java/io/github/gms/common/db/converter/EncryptedFieldConverterTest.java
  code/gms-backend/src/test/resources/application-secure.properties
  code/gms-backend/src/test/resources/application.properties
Labels: enhancement

#14 GMS-10 API Testing data will be stored securely in localStorage
  code/gms-frontend/package.json
  code/gms-frontend/src/app/common/service/secure-storage.service.spec.ts
  code/gms-frontend/src/app/common/service/secure-storage.service.ts
  code/gms-frontend/src/app/common/service/service-module.ts
  code/gms-frontend/src/app/components/api_testing/api-testing.component.spec.ts
  code/gms-frontend/src/app/components/api_testing/api-testing.component.ts
  code/gms-frontend/tsconfig.app.json
Labels: enhancement

#23 GMS-12 refresh token capability
  code/gms-backend/src/main/java/io/github/gms/auth/AuthenticationService.java
  code/gms-backend/src/main/java/io/github/gms/auth/AuthenticationServiceImpl.java
  code/gms-backend/src/main/java/io/github/gms/auth/dto/AuthenticateResponseDto.java
  code/gms-backend/src/main/java/io/github/gms/auth/model/AuthenticationDetails.java
  code/gms-backend/src/main/java/io/github/gms/auth/model/AuthenticationResponse.java
  code/gms-backend/src/main/java/io/github/gms/common/config/ApplicationConfig.java
  code/gms-backend/src/main/java/io/github/gms/common/controller/LoginController.java
  code/gms-backend/src/main/java/io/github/gms/common/controller/SystemController.java
  code/gms-backend/src/main/java/io/github/gms/common/db/converter/EncryptedFieldConverter.java
  code/gms-backend/src/main/java/io/github/gms/common/enums/JwtConfigType.java
  code/gms-backend/src/main/java/io/github/gms/common/enums/SystemProperty.java
  code/gms-backend/src/main/java/io/github/gms/common/filter/SecureHeaderInitializerFilter.java
  code/gms-backend/src/main/java/io/github/gms/common/util/Constants.java
  code/gms-backend/src/main/java/io/github/gms/common/util/CookieUtils.java
  code/gms-backend/src/main/java/io/github/gms/secure/converter/GenerateJwtRequestConverter.java
  code/gms-backend/src/main/java/io/github/gms/secure/converter/impl/GenerateJwtRequestConverterImpl.java
  code/gms-backend/src/main/java/io/github/gms/secure/service/JwtService.java
  code/gms-backend/src/main/java/io/github/gms/secure/service/impl/JwtServiceImpl.java
  code/gms-backend/src/main/java/io/github/gms/secure/service/impl/LoginServiceImpl.java
  code/gms-backend/src/test/java/io/github/gms/auth/AuthenticationServiceImplTest.java
  code/gms-backend/src/test/java/io/github/gms/common/controller/AuthenticationSecureIntegrationTest.java
  code/gms-backend/src/test/java/io/github/gms/common/controller/AuthenticationUnsecureIntegrationTest.java
  code/gms-backend/src/test/java/io/github/gms/common/filter/SecureHeaderInitializerFilterTest.java
  code/gms-backend/src/test/java/io/github/gms/common/util/CookieUtilsTest.java
  code/gms-backend/src/test/java/io/github/gms/secure/service/impl/LoginServiceImplTest.java
  code/gms-backend/src/test/java/io/github/gms/util/TestUtils.java
  code/gms-frontend/src/app/common/service/auth-service.spec.ts
  code/gms-frontend/src/app/common/service/auth-service.ts
  code/gms-frontend/src/app/components/header/header.component.spec.ts
  code/gms-frontend/src/app/components/header/header.component.ts
Labels: enhancement

#26 GMS-14 Angular 12->14 upgrade
  .github/workflows/docker-publish.yml
  .github/workflows/sonarcloud-backend.yml
  .github/workflows/sonarcloud-frontend.yml
  code/gms-backend/src/main/java/io/github/gms/api/controller/ApiController.java
  code/gms-backend/src/main/java/io/github/gms/common/enums/HeaderType.java
  code/gms-backend/src/test/java/io/github/gms/api/controller/ApiIntegrationTest.java
  code/gms-backend/src/test/java/io/github/gms/controller/ApiKeyIntegrationTest.java
  code/gms-backend/src/test/java/io/github/gms/controller/KeystoreIntegrationTest.java
  code/gms-backend/src/test/java/io/github/gms/controller/SecretIntegrationTest.java
  code/gms-backend/src/test/java/io/github/gms/util/TestUtils.java
  code/gms-frontend/angular.json
  code/gms-frontend/babel.config.js
  code/gms-frontend/jest.config.js
  code/gms-frontend/jest.config.watch.js
  code/gms-frontend/package-lock.json
  code/gms-frontend/package.json
  code/gms-frontend/setup-jest.ts
  code/gms-frontend/src/app/app.module.ts
  code/gms-frontend/src/app/common/components/pipes/date-formatter.pipe.ts
  code/gms-frontend/src/app/components/announcement/announcement-detail.component.spec.ts
  code/gms-frontend/src/app/components/announcement/announcement-list.component.spec.ts
  code/gms-frontend/src/app/components/apikey/apikey-list.component.spec.ts
  code/gms-frontend/src/app/components/event/event-list.component.spec.ts
  code/gms-frontend/src/app/components/keystore/keystore-list.component.spec.ts
  code/gms-frontend/src/app/components/messages/message-list.component.spec.ts
  code/gms-frontend/src/app/components/messages/message-module.ts
  code/gms-frontend/src/app/components/secret/secret-list.component.spec.ts
  code/gms-frontend/src/app/components/setup/setup-module.ts
  code/gms-frontend/src/app/components/setup/setup.component.spec.ts
  code/gms-frontend/src/app/components/setup/setup.component.ts
  code/gms-frontend/src/app/components/system_property/system-property-list.component.spec.ts
  code/gms-frontend/src/app/components/user/user-list.component.spec.ts
  code/gms-frontend/src/app/window.provider.ts
  code/gms-frontend/tsconfig.json
  code/gms-frontend/tsconfig.spec.json
Labels: enhancement

#28 GMS-15 check uniqueness of api key keystore and secret names
  code/gms-backend/src/main/java/io/github/gms/common/util/CookieUtils.java
  code/gms-backend/src/main/java/io/github/gms/common/util/MdcUtils.java
  code/gms-backend/src/main/java/io/github/gms/secure/entity/ApiKeyEntity.java
  code/gms-backend/src/main/java/io/github/gms/secure/repository/ApiKeyRepository.java
  code/gms-backend/src/main/java/io/github/gms/secure/repository/KeystoreRepository.java
  code/gms-backend/src/main/java/io/github/gms/secure/repository/SecretRepository.java
  code/gms-backend/src/main/java/io/github/gms/secure/service/impl/ApiKeyServiceImpl.java
  code/gms-backend/src/main/java/io/github/gms/secure/service/impl/KeystoreServiceImpl.java
  code/gms-backend/src/main/java/io/github/gms/secure/service/impl/SecretServiceImpl.java
  code/gms-backend/src/test/java/io/github/gms/secure/service/impl/ApiKeyServiceImplTest.java
  code/gms-backend/src/test/java/io/github/gms/secure/service/impl/KeystoreServiceImplTest.java
  code/gms-backend/src/test/java/io/github/gms/secure/service/impl/SecretServiceImplTest.java
  code/gms-backend/src/test/java/io/github/gms/util/TestUtils.java
  code/gms-frontend/package-lock.json
  code/gms-frontend/package.json
  code/gms-frontend/src/app/components/apikey/apikey-detail.component.html
  code/gms-frontend/src/app/components/apikey/apikey-detail.component.spec.ts
  code/gms-frontend/src/app/components/apikey/apikey-detail.component.ts
  code/gms-frontend/src/polyfills.ts
Labels: bug, enhancement

#32 GMS-18 Initial commit
  .github/workflows/sonarcloud.yml
  README.md
  batch-files/db-authentication/docker-compose.yml
  batch-files/ldap-authentication/docker-compose.yml
  code/gms-backend/pom.xml
  code/gms-frontend/package.json
  code/pom.xml
Labels: documentation, enhancement

#34 GMS-19 java client
  .github/workflows/analysis-code.yml
  .github/workflows/analysis-java-client-library.yml
  .github/workflows/app-docker-publish.yml
  .gitignore
  client-libraries/java/pom.xml
  client-libraries/java/src/main/java/io/github/gms/client/GiveMySecretClient.java
  client-libraries/java/src/main/java/io/github/gms/client/enums/KeystoreType.java
  client-libraries/java/src/main/java/io/github/gms/client/impl/GiveMySecretClientImpl.java
  client-libraries/java/src/main/java/io/github/gms/client/model/GetSecretRequest.java
  client-libraries/java/src/main/java/io/github/gms/client/model/GetSecretResponse.java
  client-libraries/java/src/main/java/io/github/gms/client/model/GiveMySecretClientConfig.java
  client-libraries/java/src/main/java/io/github/gms/client/util/ConnectionUtils.java
  client-libraries/java/src/test/java/io/github/gms/client/impl/GiveMySecretClientImplTest.java
  client-libraries/java/src/test/java/io/github/gms/client/impl/InputData.java
  client-libraries/java/src/test/java/io/github/gms/client/util/ConnectionUtilsTest.java
  client-libraries/java/src/test/resources/test.jks
  client-libraries/java/src/test/resources/test.p12
  client-samples/gms-client-sample-java-client-lib/pom.xml
  client-samples/gms-client-sample-java-client-lib/src/main/java/hu/szrnkapeter/gms/sample/MavenClientLibraryExample.java
  client-samples/gms-client-sample-java-client-lib/src/main/resources/test2.jks
Labels: documentation, enhancement

#40 GMS-23 refactor namespace of java client library
  .github/workflows/client-library-java-pr.yml
  client-libraries/java/pom.xml
  client-libraries/java/src/main/java/io/github/gms/client/GiveMySecretClient.java
  client-libraries/java/src/main/java/io/github/gms/client/enums/KeystoreType.java
  client-libraries/java/src/main/java/io/github/gms/client/impl/GiveMySecretClientImpl.java
  client-libraries/java/src/main/java/io/github/gms/client/model/GetSecretRequest.java
  client-libraries/java/src/main/java/io/github/gms/client/model/GetSecretResponse.java
  client-libraries/java/src/main/resources/checkstyle.xml
Labels: enhancement

#43 GMS-17 Fix of failed tests
  code/gms-backend/src/main/java/io/github/gms/common/config/ApplicationConfig.java
  code/gms-backend/src/main/java/io/github/gms/common/dto/SystemStatusDto.java
  code/gms-backend/src/main/java/io/github/gms/secure/service/impl/SystemServiceImpl.java
  code/gms-backend/src/main/resources/application.properties
  code/gms-backend/src/test/java/io/github/gms/common/controller/SystemStatusIntegrationTest.java
  code/gms-backend/src/test/java/io/github/gms/secure/service/impl/SystemServiceImplTest.java
Labels: bug

#45 GMS-25 Github Actions updated
  .github/workflows/app-docker-publish.yml
  .github/workflows/check-app.yml
  .github/workflows/check-client-library-java.yml
  .github/workflows/release-app.yml
  .github/workflows/release-client-library-java.yml
Labels: enhancement

#49 GMS-27 Client library removed from the main code repository
  client-libraries/java/pom.xml
  client-libraries/java/src/main/java/io/github/gms/client/GiveMySecretClient.java
  client-libraries/java/src/main/java/io/github/gms/client/enums/KeystoreType.java
  client-libraries/java/src/main/java/io/github/gms/client/impl/GiveMySecretClientImpl.java
  client-libraries/java/src/main/java/io/github/gms/client/model/GetSecretRequest.java
  client-libraries/java/src/main/java/io/github/gms/client/model/GetSecretResponse.java
  client-libraries/java/src/main/java/io/github/gms/client/model/GiveMySecretClientConfig.java
  client-libraries/java/src/main/java/io/github/gms/client/util/ConnectionUtils.java
  client-libraries/java/src/main/resources/checkstyle.xml
  client-libraries/java/src/test/java/io/github/gms/client/impl/GiveMySecretClientImplTest.java
  client-libraries/java/src/test/java/io/github/gms/client/impl/InputData.java
  client-libraries/java/src/test/java/io/github/gms/client/util/ConnectionUtilsTest.java
  client-libraries/java/src/test/resources/test.jks
  client-libraries/java/src/test/resources/test.p12
Labels: enhancement
